name: Build to gh-pages branch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: nix build

      - name: Deploy to gh-pages branch
        run: |
          git config --global user.name "ShyProton"
          git config --global user.email "shayanr1001@gmail.com"
          git switch --orphan gh-pages
          git add .
          git mv result/* .
          git rm -rf result
          git add .
          git commit -m "Update gh-pages with the latest build"
          git push -f origin gh-pages
