name: Build to gh-pages branch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: nix build

      - name: Configure git credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin "https://github-actions[bot]:${{ secrets.BOT_TOKEN }}@github.com/ShyProton/nes_emulator.git"

      - name: Stage results to gh-pages
        run: |
          git switch --orphan gh-pages
          sudo mv result/* .
          sudo rm -rf result
          git add .
          
      - name: Push to remote gh-pages
        run: |
          git commit -m "Update gh-pages with the latest build"
          git push -f origin gh-pages
