name: Build to gh-pages branch

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Install Trunk
        run: cargo install trunk

      - name: Build with Trunk
        run: trunk build --release --public-url "nes_emulator"

      - name: Deploy to gh-pages branch
        run: |
          git config --global user.name "ShyProton"
          git config --global user.email "shayanr1001@gmail.com"
          git checkout --orphan gh-pages
          git rm -rf .
          mv dist/* .
          git add .
          git commit -m "Update gh-pages with the latest build"
          git push -f origin gh-pages
